# Generated by Django 4.2.7 on 2023-12-06 21:51

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('galeria', '0008_alter_fotografia_publicado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='usuario',
            field=models.ForeignKey(default=django.contrib.auth.models.User, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
